title: "Cole Campton"
description: "Cole Campton's personal website."
#about: "Welcome to my personal website. Here I keep information on work I have done and interests I have."
#about: "You've stumbled upon a door where your mind is the key. There are none who will lend you guidance; these trials are yours to conquer alone. Entering here will take more than mere logic and strategy, but the criteria are just as hidden as what they reveal. Find yourself, and you will find the very thing hidden behind this page. Beyond here is something like a utopia — This is a mirage."
# about: "You've stumbled upon a door where your mind is the key. This is a mirage."
location: "Marin County, California"
email: cole@colecampton.com
baseurl: ""

url: "http://colecampton.com" # replace by your site's url
twitter_username: colecampton
github_username:  colecampton
author: "Cole Campton"

# google analytics tracking code, please change the value
g_analytics: "UA-97055587-1"

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "See More"
projects_btn: "Interests"
about_btn: "About"
posts_btn: "Projects"
imprint_btn: "Imprint"
name_badge: ""
#rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - pygments

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - pygments

# exclude files
exclude:
  - LICENSE
  - README.md
